spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: 839832865594-gigvtlc7aehosue0ctqn3ars0rd99maj.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile, email

jwt:
  issuer: juseung0619@gmail.com
  secret-key: adjflkqerlkmadkfljqierjokdgjlqrj32ijelwkd9auj2li4j1lkemadlkfqer09djfokadlhqtjkanvjkafdoriqo39e
  access-expired-time: 604800000   # 1 day in milliseconds
  refresh-expired-time: 604800000  # 7 days in milliseconds

