spring:
  application:
    name: execute-app

  profiles:
    active: local # default
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

---
spring:
  config:
    activate:
      on-profile: local
    import:
      - application-rds-local.yml
      - application-redis-local.yml
      - application-auth-local.yml

logging:
  level:
    com.tanji: INFO
