spring:
  application:
    name: execute-app

  profiles:
    active: local # default
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

---
spring:
  config:
    activate:
      on-profile: local
    import:
      - application-rds-local.yml
      - application-redis-local.yml
      - application-auth-local.yml
      - application-oauth-local.yml

logging:
  level:
    root: info  # 기본 로그 레벨을 info로 설정
    com.tanji: debug  # com.tanji 패키지의 로그 레벨을 debug로 설정
